version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
    - npm install --global yarn 
    - npm install --global gatsby-cli
    - yarn 
    - gatsby build
    - aws s3 sync public s3://brittanyellich.com --delete --acl public-read
    - aws cloudfront create-invalidation --distribution-id E1JIUIS8GYAMAJ --paths /*