version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
    - npm install --global yarn 
    - npm install --global gatsby-cli
    - yarn 
    - gatsby build
    - aws s3 sync public s3://brittanyellich.com --delete